name: Publish
on:
  workflow_dispatch:
jobs:
  gvm-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3   

    - name: 📩 Deploy to custom domain
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: tools.greenvisionmedia.net  
        username: tools@greenvisionmedia.net
        password: ${{secrets.FTP_PASSWORD}}
        server-dir: tools.greenvisionmedia.net/public_html/honeypot/
        local-dir: /public/
